// <auto-generated />
using System;
using BlazorMaga;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorMaga.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506151208_HtmlContentFromTopicRemove")]
    partial class HtmlContentFromTopicRemove
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.ArticlesTags", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticlesTags");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Ephemeri", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("SignId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignId");

                    b.ToTable("Ephemeris");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Nakshatra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndDeg")
                        .HasColumnType("int");

                    b.Property<int>("EndMin")
                        .HasColumnType("int");

                    b.Property<int>("NakshatraId")
                        .HasColumnType("int");

                    b.Property<int>("SignId")
                        .HasColumnType("int");

                    b.Property<int>("StartDeg")
                        .HasColumnType("int");

                    b.Property<int>("StartMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NakshatraId");

                    b.HasIndex("SignId");

                    b.ToTable("Nakshatras");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.NakshatraName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NakshatraNames");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.NakshatrasTotem", b =>
                {
                    b.Property<int>("NakshatraId")
                        .HasColumnType("int");

                    b.Property<int>("TotemId")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.HasKey("NakshatraId", "TotemId");

                    b.HasIndex("NakshatraId")
                        .IsUnique();

                    b.HasIndex("TotemId");

                    b.ToTable("NakshatrasTotems");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Sign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameLat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUkr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Signs");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Topic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.TotemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TotemNames");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Article", b =>
                {
                    b.HasOne("BlazorMaga.Shared.Entities.Topic", "Topic")
                        .WithMany("Articles")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.ArticlesTags", b =>
                {
                    b.HasOne("BlazorMaga.Shared.Entities.Article", "Article")
                        .WithMany("ArticlesTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMaga.Shared.Entities.Tag", "Tag")
                        .WithMany("ArticlesTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Ephemeri", b =>
                {
                    b.HasOne("BlazorMaga.Shared.Entities.Sign", "Sign")
                        .WithMany("Ephemeris")
                        .HasForeignKey("SignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sign");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Nakshatra", b =>
                {
                    b.HasOne("BlazorMaga.Shared.Entities.NakshatraName", "NakshatraNavigation")
                        .WithMany("Nakshatras")
                        .HasForeignKey("NakshatraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMaga.Shared.Entities.Sign", "Sign")
                        .WithMany("Nakshatras")
                        .HasForeignKey("SignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NakshatraNavigation");

                    b.Navigation("Sign");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.NakshatrasTotem", b =>
                {
                    b.HasOne("BlazorMaga.Shared.Entities.NakshatraName", "Nakshatra")
                        .WithOne("NakshatrasTotem")
                        .HasForeignKey("BlazorMaga.Shared.Entities.NakshatrasTotem", "NakshatraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMaga.Shared.Entities.TotemName", "Totem")
                        .WithMany("NakshatrasTotems")
                        .HasForeignKey("TotemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nakshatra");

                    b.Navigation("Totem");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Topic", b =>
                {
                    b.HasOne("BlazorMaga.Shared.Entities.Menu", "Menu")
                        .WithMany("Topics")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Article", b =>
                {
                    b.Navigation("ArticlesTags");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Menu", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.NakshatraName", b =>
                {
                    b.Navigation("Nakshatras");

                    b.Navigation("NakshatrasTotem");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Sign", b =>
                {
                    b.Navigation("Ephemeris");

                    b.Navigation("Nakshatras");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Tag", b =>
                {
                    b.Navigation("ArticlesTags");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.Topic", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BlazorMaga.Shared.Entities.TotemName", b =>
                {
                    b.Navigation("NakshatrasTotems");
                });
#pragma warning restore 612, 618
        }
    }
}
